package wld

import (
	"io"

	"github.com/xackery/quail/common"
)

var (
	decoders = map[int]func(r io.ReadSeeker) (common.FragmentReader, error){
		0x00: decodeDefault,
		0x01: decodePaletteFile,
		0x02: decodeUserData,
		0x03: decodeTextureList,
		0x04: decodeTexture,
		0x05: decodeTextureRef,
		0x06: decodeTwoDSprite,
		0x07: decodeTwoDSpriteRef,
		0x08: decodeThreeDSprite,
		0x09: decodeThreeDSpriteRef,
		0x0A: decodeFourDSprite,
		0x0B: decodeFourDSpriteRef,
		0x0C: decodeParticleSprite,
		0x0D: decodeParticleSpriteRef,
		0x0E: decodeCompositeSprite,
		0x0F: decodeCompositeSpriteRef,
		0x10: decodeSkeletonTrack,
		0x11: decodeSkeletonTrackRef,
		0x12: decodeTrack,
		0x13: decodeTrackRef,
		0x14: decodeModel,
		0x15: decodeModelRef,
		0x16: decodeSphere,
		0x17: decodePolyhedron,
		0x18: decodePolyhedronRef,
		0x19: decodeSphereList,
		0x1A: decodeSphereListRef,
		0x1B: decodeLight,
		0x1C: decodeLightRef,
		0x1D: decodePointLightOld,
		0x1E: decodePointLightOldRef,
		0x1F: decodeSound,
		0x20: decodeSoundRef,
		0x21: decodeWorldTree,
		0x22: decodeRegion,
		0x23: decodeActiveGeoRegion,
		0x24: decodeSkyRegion,
		0x25: decodeDirectionalLightOld,
		0x26: decodeBlitSprite,
		0x27: decodeBlitSpriteRef,
		0x28: decodePointLight,
		0x29: decodeZone,
		0x2A: decodeAmbientLight,
		0x2B: decodeDirectionalLight,
		0x2C: decodeDMSprite,
		0x2D: decodeDMSpriteRef,
		0x2E: decodeDMTrack,
		0x2F: decodeDMTrackRef,
		0x30: decodeMaterial,
		0x31: decodeMaterialList,
		0x32: decodeDMRGBTrack,
		0x33: decodeDMRGBTrackRef,
		0x34: decodeParticleCloud,
		0x35: decodeFirst,
		0x36: decodeMesh,
		0x37: decodeMeshAnimated,
	}
)
