package blender

import (
	"fmt"
	"os"
	"testing"

	"github.com/spf13/cobra"
)

func Test_export(t *testing.T) {
	eqPath := os.Getenv("EQ_PATH")
	if eqPath == "" {
		t.Skip("EQ_PATH not set")
	}

	tests := []struct {
		name    string
		path    string
		model   string
		wantErr bool
	}{
		{name: "it13926.eqg", path: eqPath, wantErr: false},
		//{name: "gequip.s3d"},                  //IT157 staff of the serpent
		//{name: "it12095.eqg", path: eqPath, wantErr: false}, // gnome on a stick
		//{name: "sin.eqg", path: eqPath, wantErr: false},     // siren
		//{name: "test.eqg", path: eqPath, wantErr: false},
		//{name: "sunderock.eqg", path: eqPath, wantErr: false},
		//{name: "gequip.s3d", path: eqPath, wantErr: false},
		//{name: "crushbone_chr.s3d", path: eqPath, wantErr: false},
		//{name: "shp_chr.s3d", path: eqPath, wantErr: false},
		//{name: "steamfontmts.eqg", path: eqPath, wantErr: false},
		//{name: "arena.eqg", path: eqPath, wantErr: false},
		//{name: "bloodfields.eqg", path: eqPath, wantErr: false},
		//{name: "ecommons_chr.s3d", path: eqPath, wantErr: false},
		//{name: "pum_chr.s3d", path: eqPath, wantErr: false},
		//{name: "crushbone.s3d", path: eqPath, wantErr: false},
		//{name: "gequip.s3d", path: eqPath, wantErr: false},
		//{name: "arena.s3d", path: eqPath, wantErr: false},
		//{name: "bal.eqg", path: eqPath, wantErr: false},
		//{name: "ans.eqg", path: eqPath, wantErr: false},
		//{name: "aro.eqg", path: eqPath, wantErr: false},
		//{name: "it13900.eqg", path: eqPath, wantErr: false},
		//{name: "xhf", path: eqPath, wantErr: false},
		//{name: "zmf", path: eqPath, wantErr: false},
		//{name: "it12043.eqg", path: eqPath, wantErr: false},
		//{name: "omensequip.eqg", path: eqPath, wantErr: false},
		/*{name: "it12312.eqg", path: eqPath, wantErr: false},
		{name: "it13900.eqg", path: eqPath, wantErr: false},
		{name: "it13901.eqg", path: eqPath, wantErr: false},
		{name: "it13902.eqg", path: eqPath, wantErr: false},
		{name: "it13903.eqg", path: eqPath, wantErr: false},
		{name: "it13904.eqg", path: eqPath, wantErr: false},
		{name: "it13905.eqg", path: eqPath, wantErr: false},
		{name: "it13906.eqg", path: eqPath, wantErr: false},
		{name: "it13907.eqg", path: eqPath, wantErr: false},
		{name: "it13908.eqg", path: eqPath, wantErr: false},
		{name: "it13909.eqg", path: eqPath, wantErr: false},
		{name: "it13910.eqg", path: eqPath, wantErr: false},
		{name: "it13911.eqg", path: eqPath, wantErr: false},
		{name: "it13912.eqg", path: eqPath, wantErr: false},
		{name: "it13913.eqg", path: eqPath, wantErr: false},
		{name: "it13914.eqg", path: eqPath, wantErr: false},
		{name: "it13915.eqg", path: eqPath, wantErr: false},
		{name: "it13916.eqg", path: eqPath, wantErr: false},
		{name: "it13917.eqg", path: eqPath, wantErr: false},
		{name: "it13918.eqg", path: eqPath, wantErr: false},
		/*{name: "it13919.eqg", path: eqPath, wantErr: false},
		{name: "it13920.eqg", path: eqPath, wantErr: false},
		{name: "it13921.eqg", path: eqPath, wantErr: false},
		{name: "it13922.eqg", path: eqPath, wantErr: false},
		{name: "it13923.eqg", path: eqPath, wantErr: false},
		{name: "it13924.eqg", path: eqPath, wantErr: false},
		{name: "it13925.eqg", path: eqPath, wantErr: false},
		{name: "it13926.eqg", path: eqPath, wantErr: false},
		{name: "it13927.eqg", path: eqPath, wantErr: false},
		{name: "it13928.eqg", path: eqPath, wantErr: false},
		{name: "it13929.eqg", path: eqPath, wantErr: false},
		{name: "it13930.eqg", path: eqPath, wantErr: false},
		{name: "it13931.eqg", path: eqPath, wantErr: false},
		{name: "it13932.eqg", path: eqPath, wantErr: false},
		{name: "it13933.eqg", path: eqPath, wantErr: false},
		{name: "it13934.eqg", path: eqPath, wantErr: false},
		{name: "it13935.eqg", path: eqPath, wantErr: false},
		{name: "it13936.eqg", path: eqPath, wantErr: false},
		{name: "it13937.eqg", path: eqPath, wantErr: false},
		{name: "it13938.eqg", path: eqPath, wantErr: false},
		{name: "it13939.eqg", path: eqPath, wantErr: false},
		{name: "it13940.eqg", path: eqPath, wantErr: false},
		{name: "it13941.eqg", path: eqPath, wantErr: false},
		{name: "it13942.eqg", path: eqPath, wantErr: false},
		{name: "it13943.eqg", path: eqPath, wantErr: false},
		{name: "it13944.eqg", path: eqPath, wantErr: false},
		{name: "it13945.eqg", path: eqPath, wantErr: false},
		{name: "it13946.eqg", path: eqPath, wantErr: false},
		{name: "it13947.eqg", path: eqPath, wantErr: false},
		{name: "it13948.eqg", path: eqPath, wantErr: false},
		{name: "it13949.eqg", path: eqPath, wantErr: false},
		{name: "it13950.eqg", path: eqPath, wantErr: false},
		{name: "it13951.eqg", path: eqPath, wantErr: false},
		{name: "it13952.eqg", path: eqPath, wantErr: false},
		{name: "it13953.eqg", path: eqPath, wantErr: false},
		{name: "it13954.eqg", path: eqPath, wantErr: false},
		{name: "it13956.eqg", path: eqPath, wantErr: false},
		{name: "it13957.eqg", path: eqPath, wantErr: false},
		{name: "it13958.eqg", path: eqPath, wantErr: false},
		{name: "it13959.eqg", path: eqPath, wantErr: false},
		{name: "it13960.eqg", path: eqPath, wantErr: false},
		{name: "it13961.eqg", path: eqPath, wantErr: false},
		{name: "it13962.eqg", path: eqPath, wantErr: false},
		{name: "it13963.eqg", path: eqPath, wantErr: false},
		{name: "it13964.eqg", path: eqPath, wantErr: false},
		{name: "it13965.eqg", path: eqPath, wantErr: false},
		{name: "it13966.eqg", path: eqPath, wantErr: false},
		{name: "it13967.eqg", path: eqPath, wantErr: false},
		{name: "it13968.eqg", path: eqPath, wantErr: false},
		{name: "it13969.eqg", path: eqPath, wantErr: false},
		{name: "it13970.eqg", path: eqPath, wantErr: false},
		{name: "it13971.eqg", path: eqPath, wantErr: false},
		{name: "it13972.eqg", path: eqPath, wantErr: false},
		{name: "it13973.eqg", path: eqPath, wantErr: false},
		{name: "it13992.eqg", path: eqPath, wantErr: false},
		{name: "it13993.eqg", path: eqPath, wantErr: false},
		{name: "it13994.eqg", path: eqPath, wantErr: false},
		{name: "it13995.eqg", path: eqPath, wantErr: false},
		{name: "it13996.eqg", path: eqPath, wantErr: false},
		{name: "it13997.eqg", path: eqPath, wantErr: false},
		{name: "it13998.eqg", path: eqPath, wantErr: false},
		{name: "it23371.eqg", path: eqPath, wantErr: false},
		{name: "it23372.eqg", path: eqPath, wantErr: false},
		{name: "it23373.eqg", path: eqPath, wantErr: false},
		{name: "it23650.eqg", path: eqPath, wantErr: false},
		{name: "it23900.eqg", path: eqPath, wantErr: false},
		{name: "it23901.eqg", path: eqPath, wantErr: false},
		{name: "it23902.eqg", path: eqPath, wantErr: false},
		{name: "it23903.eqg", path: eqPath, wantErr: false},
		{name: "it23904.eqg", path: eqPath, wantErr: false},
		{name: "it23905.eqg", path: eqPath, wantErr: false},
		{name: "it23906.eqg", path: eqPath, wantErr: false},
		{name: "it23907.eqg", path: eqPath, wantErr: false},
		{name: "it23908.eqg", path: eqPath, wantErr: false},
		{name: "it23909.eqg", path: eqPath, wantErr: false},
		{name: "it23910.eqg", path: eqPath, wantErr: false},
		{name: "it23911.eqg", path: eqPath, wantErr: false},
		{name: "it23912.eqg", path: eqPath, wantErr: false},
		{name: "it23913.eqg", path: eqPath, wantErr: false},
		{name: "it23914.eqg", path: eqPath, wantErr: false},
		{name: "it23915.eqg", path: eqPath, wantErr: false},
		{name: "it23916.eqg", path: eqPath, wantErr: false},
		{name: "it23917.eqg", path: eqPath, wantErr: false},
		{name: "it23918.eqg", path: eqPath, wantErr: false},
		{name: "it23919.eqg", path: eqPath, wantErr: false},
		{name: "it23920.eqg", path: eqPath, wantErr: false},
		{name: "it23921.eqg", path: eqPath, wantErr: false},
		{name: "it23922.eqg", path: eqPath, wantErr: false},
		{name: "it23923.eqg", path: eqPath, wantErr: false},
		{name: "it23924.eqg", path: eqPath, wantErr: false},
		{name: "it23925.eqg", path: eqPath, wantErr: false},
		{name: "it23926.eqg", path: eqPath, wantErr: false},
		{name: "it23927.eqg", path: eqPath, wantErr: false},
		{name: "it23928.eqg", path: eqPath, wantErr: false},
		{name: "it23929.eqg", path: eqPath, wantErr: false},
		{name: "it23930.eqg", path: eqPath, wantErr: false},
		{name: "it23931.eqg", path: eqPath, wantErr: false},
		{name: "it23932.eqg", path: eqPath, wantErr: false},
		{name: "it23933.eqg", path: eqPath, wantErr: false},
		{name: "it23934.eqg", path: eqPath, wantErr: false},
		{name: "it23935.eqg", path: eqPath, wantErr: false},
		{name: "it23936.eqg", path: eqPath, wantErr: false},
		{name: "it23937.eqg", path: eqPath, wantErr: false},
		{name: "it23938.eqg", path: eqPath, wantErr: false},
		{name: "it23939.eqg", path: eqPath, wantErr: false},
		{name: "it23940.eqg", path: eqPath, wantErr: false},
		{name: "it23941.eqg", path: eqPath, wantErr: false},
		{name: "it23942.eqg", path: eqPath, wantErr: false},
		{name: "it23943.eqg", path: eqPath, wantErr: false},
		{name: "it23944.eqg", path: eqPath, wantErr: false},
		{name: "it23945.eqg", path: eqPath, wantErr: false},
		{name: "it23946.eqg", path: eqPath, wantErr: false},
		{name: "it23947.eqg", path: eqPath, wantErr: false},
		{name: "it23948.eqg", path: eqPath, wantErr: false},
		{name: "it23949.eqg", path: eqPath, wantErr: false},
		{name: "it23950.eqg", path: eqPath, wantErr: false},
		{name: "it23951.eqg", path: eqPath, wantErr: false},
		{name: "it23952.eqg", path: eqPath, wantErr: false},
		{name: "it23953.eqg", path: eqPath, wantErr: false},
		{name: "it23954.eqg", path: eqPath, wantErr: false},
		{name: "it23955.eqg", path: eqPath, wantErr: false},
		{name: "it23956.eqg", path: eqPath, wantErr: false},
		{name: "it23957.eqg", path: eqPath, wantErr: false},
		{name: "it23958.eqg", path: eqPath, wantErr: false},
		{name: "it23959.eqg", path: eqPath, wantErr: false},
		{name: "it23960.eqg", path: eqPath, wantErr: false},
		{name: "it23961.eqg", path: eqPath, wantErr: false},
		{name: "it23962.eqg", path: eqPath, wantErr: false},
		{name: "it23963.eqg", path: eqPath, wantErr: false},
		{name: "it23964.eqg", path: eqPath, wantErr: false},
		{name: "it23965.eqg", path: eqPath, wantErr: false},
		{name: "it23966.eqg", path: eqPath, wantErr: false},
		{name: "it23967.eqg", path: eqPath, wantErr: false},
		{name: "it23968.eqg", path: eqPath, wantErr: false},
		{name: "it23969.eqg", path: eqPath, wantErr: false},
		{name: "it23970.eqg", path: eqPath, wantErr: false},
		{name: "it23971.eqg", path: eqPath, wantErr: false},
		{name: "it23972.eqg", path: eqPath, wantErr: false},
		{name: "it23973.eqg", path: eqPath, wantErr: false},
		{name: "it23974.eqg", path: eqPath, wantErr: false},
		{name: "it23975.eqg", path: eqPath, wantErr: false},
		{name: "it23976.eqg", path: eqPath, wantErr: false},
		{name: "it23977.eqg", path: eqPath, wantErr: false},
		{name: "it23978.eqg", path: eqPath, wantErr: false},
		{name: "it23979.eqg", path: eqPath, wantErr: false},
		{name: "it23980.eqg", path: eqPath, wantErr: false},
		{name: "it23981.eqg", path: eqPath, wantErr: false},
		{name: "it23982.eqg", path: eqPath, wantErr: false},
		{name: "it23983.eqg", path: eqPath, wantErr: false},
		{name: "it23984.eqg", path: eqPath, wantErr: false},
		{name: "it23985.eqg", path: eqPath, wantErr: false},
		{name: "it23986.eqg", path: eqPath, wantErr: false},
		{name: "it23987.eqg", path: eqPath, wantErr: false},
		{name: "it23988.eqg", path: eqPath, wantErr: false},
		{name: "it23989.eqg", path: eqPath, wantErr: false},
		{name: "it23990.eqg", path: eqPath, wantErr: false},
		{name: "it23991.eqg", path: eqPath, wantErr: false},
		{name: "it23992.eqg", path: eqPath, wantErr: false},
		{name: "it23993.eqg", path: eqPath, wantErr: false},
		{name: "it23994.eqg", path: eqPath, wantErr: false},
		{name: "it23995.eqg", path: eqPath, wantErr: false},
		{name: "it23996.eqg", path: eqPath, wantErr: false},
		{name: "it23997.eqg", path: eqPath, wantErr: false},
		{name: "it60001.eqg", path: eqPath, wantErr: false},
		{name: "it60002.eqg", path: eqPath, wantErr: false},*/

	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.path == "" {
				tt.path = eqPath
			}
			if err := export(&cobra.Command{}, []string{fmt.Sprintf("%s/%s", tt.path, tt.name), "test/"}); (err != nil) != tt.wantErr {
				t.Errorf("export() error = %v, path: eqPath, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
