package blender

import (
	"fmt"
	"os"
	"testing"

	"github.com/spf13/cobra"
)

func Test_export(t *testing.T) {
	eqPath := os.Getenv("EQ_PATH")
	if eqPath == "" {
		t.Skip("EQ_PATH not set")
	}

	type args struct {
		cmd  *cobra.Command
		args []string
	}
	tests := []struct {
		name    string
		args    args
		wantErr bool
	}{
		//{name: "arena", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/arena.eqg", eqPath), "test/"}}, wantErr: false},
		//{name: "steamfontmts", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/steamfontmts.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13900", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13900.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "xhf", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/xhf.eqg", eqPath), "test/"}}, wantErr: false},
		//{name: "zmf", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/zmf.eqg", eqPath), "test/"}}, wantErr: false},
		//{name: "it12043.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it12043.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "gnome-wave-it12095.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it12095.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "omensequip.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/omensequip.eqg", eqPath), "test/"}}, wantErr: false},

		/*{name: "it12312.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it12312.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13900.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13900.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13901.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13901.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13902.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13902.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13903.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13903.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13904.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13904.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13905.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13905.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13906.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13906.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13907.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13907.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13908.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13908.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13909.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13909.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13910.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13910.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13911.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13911.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13912.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13912.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13913.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13913.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13914.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13914.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13915.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13915.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13916.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13916.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13917.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13917.eqg", eqPath), "test/"}}, wantErr: false},
		{name: "it13918.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13918.eqg", eqPath), "test/"}}, wantErr: false},
		/*{name: "it13919.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13919.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13920.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13920.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13921.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13921.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13922.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13922.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13923.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13923.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13924.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13924.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13925.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13925.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13926.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13926.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13927.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13927.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13928.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13928.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13929.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13929.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13930.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13930.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13931.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13931.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13932.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13932.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13933.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13933.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13934.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13934.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13935.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13935.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13936.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13936.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13937.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13937.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13938.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13938.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13939.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13939.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13940.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13940.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13941.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13941.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13942.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13942.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13943.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13943.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13944.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13944.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13945.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13945.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13946.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13946.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13947.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13947.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13948.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13948.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13949.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13949.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13950.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13950.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13951.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13951.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13952.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13952.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13953.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13953.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13954.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13954.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13956.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13956.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13957.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13957.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13958.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13958.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13959.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13959.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13960.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13960.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13961.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13961.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13962.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13962.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13963.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13963.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13964.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13964.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13965.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13965.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13966.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13966.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13967.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13967.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13968.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13968.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13969.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13969.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13970.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13970.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13971.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13971.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13972.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13972.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13973.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13973.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13992.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13992.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13993.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13993.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13994.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13994.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13995.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13995.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13996.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13996.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13997.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13997.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it13998.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it13998.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23371.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23371.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23372.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23372.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23373.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23373.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23650.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23650.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23900.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23900.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23901.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23901.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23902.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23902.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23903.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23903.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23904.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23904.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23905.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23905.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23906.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23906.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23907.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23907.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23908.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23908.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23909.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23909.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23910.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23910.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23911.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23911.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23912.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23912.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23913.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23913.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23914.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23914.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23915.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23915.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23916.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23916.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23917.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23917.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23918.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23918.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23919.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23919.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23920.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23920.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23921.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23921.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23922.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23922.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23923.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23923.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23924.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23924.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23925.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23925.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23926.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23926.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23927.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23927.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23928.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23928.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23929.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23929.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23930.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23930.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23931.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23931.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23932.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23932.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23933.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23933.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23934.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23934.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23935.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23935.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23936.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23936.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23937.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23937.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23938.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23938.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23939.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23939.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23940.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23940.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23941.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23941.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23942.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23942.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23943.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23943.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23944.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23944.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23945.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23945.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23946.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23946.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23947.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23947.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23948.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23948.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23949.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23949.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23950.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23950.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23951.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23951.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23952.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23952.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23953.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23953.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23954.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23954.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23955.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23955.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23956.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23956.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23957.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23957.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23958.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23958.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23959.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23959.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23960.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23960.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23961.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23961.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23962.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23962.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23963.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23963.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23964.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23964.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23965.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23965.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23966.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23966.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23967.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23967.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23968.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23968.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23969.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23969.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23970.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23970.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23971.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23971.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23972.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23972.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23973.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23973.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23974.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23974.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23975.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23975.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23976.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23976.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23977.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23977.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23978.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23978.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23979.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23979.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23980.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23980.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23981.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23981.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23982.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23982.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23983.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23983.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23984.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23984.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23985.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23985.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23986.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23986.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23987.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23987.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23988.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23988.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23989.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23989.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23990.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23990.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23991.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23991.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23992.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23992.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23993.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23993.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23994.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23994.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23995.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23995.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23996.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23996.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it23997.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it23997.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it60001.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it60001.eqg", eqPath), "test/"}}. wantErr: false},
		{name: "it60002.eqg", args: args{cmd: &cobra.Command{}, args: []string{fmt.Sprintf("%s/it60002.eqg", eqPath), "test/"}}. wantErr: false},*/

	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := export(tt.args.cmd, tt.args.args); (err != nil) != tt.wantErr {
				t.Errorf("export() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
