name: Tag Prep Release
on:
  push:
    tags:
      - 'v*.*.*'  # Matches version tags like v1.2.3
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go get ./...
      - run: go test -tags ci ./...
      - run: make sanitize
      - run: make build-all
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          title: ${{ github.ref }}
          files: |
            bin/quail-linux
            bin/quail.exe
            bin/quail-darwin
